### Request List of all (user related) books

GET http://localhost:3000/api/manage/list-books
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIkMmIkMTAkaHJrdEtTMWRWOEVRREs5Vk9maDZJTy9YOXBGdHZrNjVnTnFNSml2SXpELnA2MjV5eGJmaTYiLCJpYXQiOjE2ODM4ODA1NjEsImV4cCI6MTY4Mzg4MTE2MX0.9rLjnom_FkM6_5i-bBHHvyV9KuhTgAyIEiqC7xiOSYk