### Request List of all (user related) books

GET http://localhost:3000/api/manage/list-books
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIkMmIkMTAkaHJrdEtTMWRWOEVRREs5Vk9maDZJTy9WSEdkdWhUTi44d2pyRDVDbzEvQm53LjNJMDlmeUMiLCJpYXQiOjE2ODM4ODk2MjUsImV4cCI6MTY4Mzg5MDIyNX0.PH6hwQBAX6TznkC_fqN_Tn6rrBHAaAaq_-8GX_zg67w