### Request List of all (user related) books

GET http://localhost:3000/api/manage/list-books
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIkMmIkMTAkaHJrdEtTMWRWOEVRREs5Vk9maDZJT2RieE9GTEpYRy4uNWRicU5TZ204YlR2ai9xTU42VzYiLCJpYXQiOjE2ODM3NDQyNzMsImV4cCI6MTY4Mzc0NDg3M30.AgTd46yY_aQNdTk4ifyi2NjliyNRUSjQK6Txryd92tw