### Request for authentification Method
POST http://localhost:3000/api/generate/create-new
Content-Type: application/json

{
  "child_name": "Timy",
  "child_favColor": "Rosa",
  "child_favAnimals": "Schweine",
  "child_age": "9",
  "child_country": "Deutschland",
  "child_language": "deutsch",
  "child_gender": "maennlich",

  "topic_moralType": "Hilfsbereitschaft",
  "topic_chapterCount": "5",
  "topic_imageStyle": "Comic",
  "topic_specialTopic": "Piraten",
}